import type { Metadata } from 'next'
import { Figtree } from 'next/font/google'
import './globals.css'
import { colors } from './styles'

const figtree = Figtree({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Blog Preview Card',
  description: 'Generated by create next app',
}

const variants = {
  background: [
    'bg-[#f4d04e]', 'bg-[#ffffff]',
    'bg-[#808080]', 'bg-[#121212]',
  ],
  text: [
    'text-[#f4d04e]', 'text-[#ffffff]',
    'text-[#808080]', 'text-[#121212]',
  ],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={figtree.className}>
        <div className={`bg-${colors.primary.yellow}`}>
          <div className={`flex flex-col items-center justify-center min-h-screen`}>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
